name: integration_test
description: Runs tests that use the flutter_test API as integration tests.
version: 0.9.0
homepage: https://github.com/flutter/plugins/tree/master/packages/integration_test

environment:
  sdk: ">=2.2.2 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <2.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  path: ^1.8.0
  vm_service: ^7.3.0

dev_dependencies:
  pedantic: ^1.11.1
  mockito: ^5.1.0

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.integration_test
        pluginClass: IntegrationTestPlugin
      ios:
        pluginClass: IntegrationTestPlugin
