name: local_auth_example
version: 1.0.0
description: Demonstrates how to use the local_auth plugin.
environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.20.4 <2.10.0"
dependencies:
  flutter:
    sdk: flutter
  local_auth:
    path: ../

dev_dependencies:
  integration_test:
    path: ../../integration_test
  flutter_driver:
    sdk: flutter
  pedantic: ^1.8.0

flutter:
  uses-material-design: true
